"""outbound_webhooks

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c82c5f4b4e'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_webhook_events',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', name='outboundeventstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_webhook_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhook_delivery_attempts',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('event_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbound_webhook_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_attempts_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_attempts_event_id'))

    op.drop_table('webhook_delivery_attempts')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_tenant_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_events_tenant_id'))

    op.drop_table('outbound_webhook_events')
    # ### end Alembic commands ###
