"""Drop project_id from subscriptions invoices invoice_line_items payment_attempts

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7b8032fe51'
down_revision: Union[str, Sequence[str], None] = '3a83030c0e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_project_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_audit_logs_project_id', 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_invoice_line_items_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_invoices_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_events_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_outbound_webhook_events_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attempts_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_payment_attempts_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_plans_project_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_plans_project_id', 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_subscriptions_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_project_id'))
        batch_op.drop_constraint(batch_op.f('fk_webhook_endpoints_project_id'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_webhook_endpoints_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_subscriptions_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_subscriptions_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plans_project_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plans_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('project_id',
               nullable=False)

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_payment_attempts_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_payment_attempts_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_outbound_webhook_events_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_outbound_webhook_events_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_invoices_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_invoices_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_invoice_line_items_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_invoice_line_items_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_project_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_project_id'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('project_id',
               nullable=False)

    # ### end Alembic commands ###
