"""Add portal fields to customer

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304e1e5fdbac'
down_revision: Union[str, Sequence[str], None] = '45b1846139c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_token_slug', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('portal_pin_hash', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_portal_token_slug'), ['portal_token_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_portal_token_slug'))
        batch_op.drop_column('portal_pin_hash')
        batch_op.drop_column('portal_token_slug')

    # ### end Alembic commands ###
