"""add_is_test_to_subscription_pages

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b1846139c0'
down_revision: Union[str, Sequence[str], None] = '28d9975b2395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index(batch_op.f('ix_subscription_pages_is_test'), ['is_test'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_pages_is_test'))
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###
