"""add_subscription_pages

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f31383fdeda'
down_revision: Union[str, Sequence[str], None] = '0e7b8032fe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_pages',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('plan_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_pages_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscription_pages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_pages_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_pages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_pages_project_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_pages_code'))

    op.drop_table('subscription_pages')
    # ### end Alembic commands ###
