"""Add projects table and project_id to resources

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c2f6cc90a'
down_revision: Union[str, Sequence[str], None] = 'ea73c2c18b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_logs_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_customers_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_customers_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoice_line_items_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_invoice_line_items_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_invoices_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_outbound_webhook_events_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_outbound_webhook_events_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_attempts_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_payment_attempts_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_methods_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_payment_methods_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_plans_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_plans_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reconciliation_discrepancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=True))
        batch_op.create_index(batch_op.f('ix_reconciliation_discrepancies_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_reconciliation_discrepancies_project_id', 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_subscriptions_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_subscriptions_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(native_uuid=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_webhook_endpoints_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_constraint('fk_webhook_endpoints_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscriptions_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('reconciliation_discrepancies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reconciliation_discrepancies_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reconciliation_discrepancies_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plans_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plans_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_methods_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_methods_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_attempts_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_attempts_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outbound_webhook_events_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_events_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_line_items_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
