"""add_card_meta_and_portal_columns_to_customers

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da870e8bff'
down_revision: Union[str, Sequence[str], None] = '304e1e5fdbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_last4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_brand', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('card_brand')
        batch_op.drop_column('card_last4')

    # ### end Alembic commands ###
