"""add_is_test_to_resource_tables

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44808cabe2f'
down_revision: Union[str, Sequence[str], None] = '4f31383fdeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_customers_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoices_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_outbound_webhook_events_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_attempts_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_methods_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_plans_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('reconciliation_discrepancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reconciliation_discrepancies_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_subscriptions_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_is_test'), ['is_test'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('reconciliation_discrepancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_discrepancies_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attempts_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('outbound_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_events_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_is_test'))
        batch_op.drop_column('is_test')

    # ### end Alembic commands ###
