"""initial_models

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07ab7fc2768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('customers',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', 'month', 'year', name='planinterval', native_enum=False), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('trial_period_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='planstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('customer_id', sa.TEXT(), nullable=False),
    sa.Column('type', sa.Enum('card', 'bank_transfer', 'wallet', name='paymentmethodtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'detached', name='paymentmethodstatus', native_enum=False), nullable=False),
    sa.Column('provider_token', sa.String(length=512), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_customer_id'), 'payment_methods', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_tenant_id'), 'payment_methods', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_methods_tenant_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_customer_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('tenants')
    # ### end Alembic commands ###
